import type { RegistrationField } from '../types';

export const DEFAULT_FAMILY_FIELDS: RegistrationField[] = [
    // Mandatory fields
    {
        id: 'family-head-name',
        label: 'Family Head Name',
        fieldName: 'headName',
        type: 'text',
        category: 'family',
        isMandatory: true,
        isEnabled: true,
    },
    {
        id: 'house-name',
        label: 'House Name / Number',
        fieldName: 'houseName',
        type: 'text',
        category: 'family',
        isMandatory: true,
        isEnabled: true,
    },
    {
        id: 'address',
        label: 'Address',
        fieldName: 'address',
        type: 'text',
        category: 'family',
        isMandatory: true,
        isEnabled: true,
    },
    {
        id: 'ward',
        label: 'Ward / Area',
        fieldName: 'ward',
        type: 'select',
        category: 'family',
        isMandatory: true,
        isEnabled: true,
        options: ['Ward 1', 'Ward 2', 'Ward 3', 'Ward 4'],
    },
    {
        id: 'primary-phone',
        label: 'Primary Contact Number',
        fieldName: 'primaryPhone',
        type: 'tel',
        category: 'family',
        isMandatory: true,
        isEnabled: true,
    },

    // Optional fields
    {
        id: 'mahallu-number',
        label: 'Mahallu Number',
        fieldName: 'mahalluNumber',
        type: 'text',
        category: 'family',
        isMandatory: false,
        isEnabled: true,
    },
    {
        id: 'alternate-phone',
        label: 'Alternate Contact Number',
        fieldName: 'alternatePhone',
        type: 'tel',
        category: 'family',
        isMandatory: false,
        isEnabled: true,
    },
    {
        id: 'income-category',
        label: 'Monthly Income Range',
        fieldName: 'incomeCategory',
        type: 'select',
        category: 'family',
        isMandatory: false,
        isEnabled: true,
        options: ['Below ₹10,000', '₹10,000 - ₹50,000', 'Above ₹50,000'],
    },
    {
        id: 'housing-type',
        label: 'Housing Type',
        fieldName: 'housingType',
        type: 'select',
        category: 'family',
        isMandatory: false,
        isEnabled: true,
        options: ['Own House', 'Rented', 'Other'],
    },
    {
        id: 'ration-card',
        label: 'Ration Card Type',
        fieldName: 'rationCardType',
        type: 'select',
        category: 'family',
        isMandatory: false,
        isEnabled: true,
        options: ['APL', 'BPL', 'AAY'],
    },
];

export const DEFAULT_MEMBER_FIELDS: RegistrationField[] = [
    // Mandatory fields
    {
        id: 'member-name',
        label: 'Full Name',
        fieldName: 'name',
        type: 'text',
        category: 'member',
        isMandatory: true,
        isEnabled: true,
    },
    {
        id: 'member-gender',
        label: 'Gender',
        fieldName: 'gender',
        type: 'select',
        category: 'member',
        isMandatory: true,
        isEnabled: true,
        options: ['Male', 'Female'],
    },
    {
        id: 'member-dob',
        label: 'Date of Birth',
        fieldName: 'dob',
        type: 'date',
        category: 'member',
        isMandatory: true,
        isEnabled: true,
    },
    {
        id: 'member-relationship',
        label: 'Relationship',
        fieldName: 'relationship',
        type: 'select',
        category: 'member',
        isMandatory: true,
        isEnabled: true,
        options: ['Head', 'Spouse', 'Child', 'Parent', 'Sibling', 'Other'],
    },

    // Optional fields
    {
        id: 'member-education',
        label: 'Education',
        fieldName: 'education',
        type: 'select',
        category: 'member',
        isMandatory: false,
        isEnabled: true,
        options: ['Primary', 'Secondary', 'Graduate', 'Post Graduate', 'Other'],
    },
    {
        id: 'member-occupation',
        label: 'Occupation',
        fieldName: 'occupation',
        type: 'text',
        category: 'member',
        isMandatory: false,
        isEnabled: true,
    },
    {
        id: 'member-phone',
        label: 'Contact Number',
        fieldName: 'phone',
        type: 'tel',
        category: 'member',
        isMandatory: false,
        isEnabled: false, // Disabled by default
    },
    {
        id: 'member-email',
        label: 'Email Address',
        fieldName: 'email',
        type: 'email',
        category: 'member',
        isMandatory: false,
        isEnabled: false, // Disabled by default
    },
];
